// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251015213820_AddingACheckupStatusToFridgeVisittaleOnDb")]
    partial class AddingACheckupStatusToFridgeVisittaleOnDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FridgeId");

                    b.ToTable("tblAllocations");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("BusinessDocumentData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BusinessDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblCustomers");
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblEmployee");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentalPricePerMonth")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeId");

                    b.ToTable("tblFridges");

                    b.HasData(
                        new
                        {
                            FridgeId = 1,
                            AvailabilityStatus = "Available",
                            Brand = "Samsung",
                            CapacityLiters = 250,
                            Description = "Energy efficient fridge with frost-free technology",
                            ImageUrl = "/Images/Fridges/0f189537-b86b-46ed-88b0-697d64518b86.jpg",
                            Location = "Durban",
                            Model = "RT28A",
                            RentalPricePerMonth = 450.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 2,
                            AvailabilityStatus = "Available",
                            Brand = "LG",
                            CapacityLiters = 260,
                            Description = "Smart inverter compressor for energy savings",
                            ImageUrl = "/Images/Fridges/3af820d9-c376-4432-8a69-db81af07350d.jpg",
                            Location = "Johannesburg",
                            Model = "GL-T292",
                            RentalPricePerMonth = 480.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 3,
                            AvailabilityStatus = "Rented",
                            Brand = "Hisense",
                            CapacityLiters = 320,
                            Description = "Spacious design with humidity control",
                            ImageUrl = "Images/Fridges/1bde2bd0-9345-4868-bf0e-3a568b75b45d.jpg",
                            Location = "Cape Town",
                            Model = "H370BI",
                            RentalPricePerMonth = 520.0,
                            Type = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeId = 4,
                            AvailabilityStatus = "Available",
                            Brand = "Defy",
                            CapacityLiters = 350,
                            Description = "A+ energy rated with multi-airflow system",
                            ImageUrl = "Images/Fridges/3af820d9-c376-4432-8a69-db81af07350d.jpg",
                            Location = "Pretoria",
                            Model = "DAC621",
                            RentalPricePerMonth = 550.0,
                            Type = "Combi Fridge"
                        },
                        new
                        {
                            FridgeId = 5,
                            AvailabilityStatus = "Available",
                            Brand = "Whirlpool",
                            CapacityLiters = 200,
                            Description = "Compact and efficient single door fridge",
                            ImageUrl = "Images/Fridges/3fab2301-7b43-489c-a5eb-a4a84e146a0c.jpg",
                            Location = "Durban",
                            Model = "WDE205",
                            RentalPricePerMonth = 400.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 6,
                            AvailabilityStatus = "Rented",
                            Brand = "Bosch",
                            CapacityLiters = 350,
                            Description = "No frost cooling with LED lighting",
                            ImageUrl = "Images/Fridges/4ff51e2e-eb52-464d-9bd0-9b93671b7b1d.jpg",
                            Location = "Port Elizabeth",
                            Model = "KDN42",
                            RentalPricePerMonth = 600.0,
                            Type = "Frost Free"
                        },
                        new
                        {
                            FridgeId = 7,
                            AvailabilityStatus = "Available",
                            Brand = "Smeg",
                            CapacityLiters = 270,
                            Description = "Stylish retro fridge with adjustable shelves",
                            ImageUrl = "Images/Fridges/5f3c62bc-b7a1-4099-8453-0562449c1eba.jpg",
                            Location = "Johannesburg",
                            Model = "FAB28",
                            RentalPricePerMonth = 650.0,
                            Type = "Retro Style"
                        },
                        new
                        {
                            FridgeId = 8,
                            AvailabilityStatus = "Available",
                            Brand = "Kelvinator",
                            CapacityLiters = 265,
                            Description = "Affordable fridge with efficient cooling",
                            ImageUrl = "Images/Fridges/06d99650-49bb-46a0-9c87-479b064e20cf.jpg.jpg",
                            Location = "Cape Town",
                            Model = "KRF265",
                            RentalPricePerMonth = 430.0,
                            Type = "Top Mount"
                        },
                        new
                        {
                            FridgeId = 9,
                            AvailabilityStatus = "Rented",
                            Brand = "Siemens",
                            CapacityLiters = 360,
                            Description = "No frost with multi-airflow system",
                            ImageUrl = "Images/Fridges/6c99da3a-7e53-4a54-a4c2-179ba50f4552.jpg",
                            Location = "Pretoria",
                            Model = "KG36N",
                            RentalPricePerMonth = 590.0,
                            Type = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeId = 10,
                            AvailabilityStatus = "Available",
                            Brand = "Haier",
                            CapacityLiters = 290,
                            Description = "Toughened glass shelves and energy efficient",
                            ImageUrl = "Images/Fridges/7a5c9f14-43cc-4b88-98a1-2cd4f34b355a.jpg",
                            Location = "Durban",
                            Model = "HRF290",
                            RentalPricePerMonth = 470.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 11,
                            AvailabilityStatus = "Available",
                            Brand = "Hisense",
                            CapacityLiters = 310,
                            Description = "Low noise and efficient compressor",
                            ImageUrl = "Images/Fridges/7a5ef7b8-7c58-4d8e-bf27-3c1c9a911b45.jpg",
                            Location = "Bloemfontein",
                            Model = "H310BI",
                            RentalPricePerMonth = 500.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 12,
                            AvailabilityStatus = "Rented",
                            Brand = "Defy",
                            CapacityLiters = 420,
                            Description = "LED display and water dispenser",
                            ImageUrl = "Images/Fridges/8e2d92bf-c306-4688-89f5-019d76a9539b.jpg",
                            Location = "Cape Town",
                            Model = "DAC700",
                            RentalPricePerMonth = 700.0,
                            Type = "Side by Side"
                        },
                        new
                        {
                            FridgeId = 13,
                            AvailabilityStatus = "Available",
                            Brand = "LG",
                            CapacityLiters = 282,
                            Description = "Smart cooling with WiFi control",
                            ImageUrl = "Images/Fridges/7e4c22d6-9a91-4d0c-83db-95856b2a30f0.jpg",
                            Location = "Durban",
                            Model = "GL-Q282",
                            RentalPricePerMonth = 530.0,
                            Type = "Smart Inverter"
                        },
                        new
                        {
                            FridgeId = 14,
                            AvailabilityStatus = "Rented",
                            Brand = "Samsung",
                            CapacityLiters = 340,
                            Description = "Twin cooling system for freshness",
                            ImageUrl = "Images/Fridges/16eaa25a-e6ad-4584-869f-79c59db95573.jpg",
                            Location = "Pretoria",
                            Model = "RT34A",
                            RentalPricePerMonth = 560.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 15,
                            AvailabilityStatus = "Available",
                            Brand = "Whirlpool",
                            CapacityLiters = 500,
                            Description = "High capacity with 6th sense technology",
                            ImageUrl = "Images/Fridges/33b3ec74-7862-44e1-afa0-4c4a42689a9f.jpg",
                            Location = "Johannesburg",
                            Model = "WDE520",
                            RentalPricePerMonth = 750.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 16,
                            AvailabilityStatus = "Available",
                            Brand = "Bosch",
                            CapacityLiters = 400,
                            Description = "Energy efficient and silent operation",
                            ImageUrl = "Images/Fridges/59a41e73-af93-465b-a5aa-f0d7cf37fe2c.jpg",
                            Location = "Durban",
                            Model = "KDN43",
                            RentalPricePerMonth = 610.0,
                            Type = "Frost Free"
                        },
                        new
                        {
                            FridgeId = 17,
                            AvailabilityStatus = "Rented",
                            Brand = "Smeg",
                            CapacityLiters = 300,
                            Description = "Vintage design with modern efficiency",
                            ImageUrl = "Images/Fridges/be54bce5-b511-4946-8f3a-55ae0a65ec35.jpg",
                            Location = "Cape Town",
                            Model = "FAB32",
                            RentalPricePerMonth = 670.0,
                            Type = "Retro Style"
                        },
                        new
                        {
                            FridgeId = 18,
                            AvailabilityStatus = "Available",
                            Brand = "Siemens",
                            CapacityLiters = 390,
                            Description = "Multi-airflow and easy-clean interior",
                            ImageUrl = "Images/Fridges/dff205af-9cde-4e97-876d-3b9a603e6459.jpg",
                            Location = "Johannesburg",
                            Model = "KG39N",
                            RentalPricePerMonth = 620.0,
                            Type = "Combi Fridge"
                        },
                        new
                        {
                            FridgeId = 19,
                            AvailabilityStatus = "Available",
                            Brand = "Haier",
                            CapacityLiters = 330,
                            Description = "Tough build and fast cooling",
                            ImageUrl = "Images/Fridges/45189b3d-8e97-49b3-8c90-47ec9d6db6b9.jpg",
                            Location = "Pretoria",
                            Model = "HRF330",
                            RentalPricePerMonth = 500.0,
                            Type = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeId = 20,
                            AvailabilityStatus = "Rented",
                            Brand = "Defy",
                            CapacityLiters = 473,
                            Description = "Spacious and frost-free design",
                            ImageUrl = "Images/Fridges/2634148d-20b9-40c2-9849-3566df69f859.jpg",
                            Location = "Durban",
                            Model = "DAC473",
                            RentalPricePerMonth = 720.0,
                            Type = "Side by Side"
                        });
                });

            modelBuilder.Entity("Project.Models.FridgeInStock", b =>
                {
                    b.Property<int>("FridgeInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeInStockId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("FridgeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FridgeInStockId");

                    b.HasIndex("FridgeId");

                    b.ToTable("tblFridgeInStocks");

                    b.HasData(
                        new
                        {
                            FridgeInStockId = 1,
                            Condition = "Excellent",
                            FridgeId = 1,
                            FridgeNo = "FRG001",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 2,
                            Condition = "Good",
                            FridgeId = 1,
                            FridgeNo = "FRG002",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 3,
                            Condition = "Excellent",
                            FridgeId = 2,
                            FridgeNo = "FRG003",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 4,
                            Condition = "Good",
                            FridgeId = 2,
                            FridgeNo = "FRG004",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 5,
                            Condition = "Fair",
                            FridgeId = 3,
                            FridgeNo = "FRG005",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 6,
                            Condition = "Excellent",
                            FridgeId = 3,
                            FridgeNo = "FRG006",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 7,
                            Condition = "Good",
                            FridgeId = 4,
                            FridgeNo = "FRG007",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 8,
                            Condition = "Fair",
                            FridgeId = 4,
                            FridgeNo = "FRG008",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 9,
                            Condition = "Good",
                            FridgeId = 5,
                            FridgeNo = "FRG009",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 10,
                            Condition = "Excellent",
                            FridgeId = 5,
                            FridgeNo = "FRG010",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 11,
                            Condition = "Good",
                            FridgeId = 6,
                            FridgeNo = "FRG011",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Port Elizabeth",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 12,
                            Condition = "Excellent",
                            FridgeId = 6,
                            FridgeNo = "FRG012",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Port Elizabeth",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 13,
                            Condition = "Excellent",
                            FridgeId = 7,
                            FridgeNo = "FRG013",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 14,
                            Condition = "Fair",
                            FridgeId = 7,
                            FridgeNo = "FRG014",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 15,
                            Condition = "Good",
                            FridgeId = 8,
                            FridgeNo = "FRG015",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 16,
                            Condition = "Excellent",
                            FridgeId = 8,
                            FridgeNo = "FRG016",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 17,
                            Condition = "Good",
                            FridgeId = 9,
                            FridgeNo = "FRG017",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 18,
                            Condition = "Excellent",
                            FridgeId = 9,
                            FridgeNo = "FRG018",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 19,
                            Condition = "Fair",
                            FridgeId = 10,
                            FridgeNo = "FRG019",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 20,
                            Condition = "Excellent",
                            FridgeId = 10,
                            FridgeNo = "FRG020",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 21,
                            Condition = "Excellent",
                            FridgeId = 11,
                            FridgeNo = "FRG021",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bloemfontein",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 22,
                            Condition = "Fair",
                            FridgeId = 11,
                            FridgeNo = "FRG022",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bloemfontein",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 23,
                            Condition = "Good",
                            FridgeId = 12,
                            FridgeNo = "FRG023",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 24,
                            Condition = "Excellent",
                            FridgeId = 12,
                            FridgeNo = "FRG024",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 25,
                            Condition = "Good",
                            FridgeId = 13,
                            FridgeNo = "FRG025",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 26,
                            Condition = "Fair",
                            FridgeId = 13,
                            FridgeNo = "FRG026",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 27,
                            Condition = "Excellent",
                            FridgeId = 14,
                            FridgeNo = "FRG027",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 28,
                            Condition = "Good",
                            FridgeId = 14,
                            FridgeNo = "FRG028",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 29,
                            Condition = "Excellent",
                            FridgeId = 15,
                            FridgeNo = "FRG029",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 30,
                            Condition = "Fair",
                            FridgeId = 15,
                            FridgeNo = "FRG030",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 31,
                            Condition = "Excellent",
                            FridgeId = 16,
                            FridgeNo = "FRG031",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 32,
                            Condition = "Good",
                            FridgeId = 16,
                            FridgeNo = "FRG032",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 33,
                            Condition = "Fair",
                            FridgeId = 17,
                            FridgeNo = "FRG033",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 34,
                            Condition = "Excellent",
                            FridgeId = 17,
                            FridgeNo = "FRG034",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Cape Town",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 35,
                            Condition = "Good",
                            FridgeId = 18,
                            FridgeNo = "FRG035",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 36,
                            Condition = "Fair",
                            FridgeId = 18,
                            FridgeNo = "FRG036",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Johannesburg",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 37,
                            Condition = "Excellent",
                            FridgeId = 19,
                            FridgeNo = "FRG037",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 38,
                            Condition = "Good",
                            FridgeId = 19,
                            FridgeNo = "FRG038",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Pretoria",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 39,
                            Condition = "Fair",
                            FridgeId = 20,
                            FridgeNo = "FRG039",
                            IsAvailable = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        },
                        new
                        {
                            FridgeInStockId = 40,
                            Condition = "Excellent",
                            FridgeId = 20,
                            FridgeNo = "FRG040",
                            IsAvailable = true,
                            LastMaintenanceDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Durban",
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Project.Models.FridgeVisit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("CheckupStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerApproval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("RequestHeaderId");

                    b.ToTable("tblFridgeVisits");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.Property<int>("RequestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestDetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RequestHeaderId")
                        .HasColumnType("int");

                    b.HasKey("RequestDetailId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("RequestHeaderId");

                    b.ToTable("tblRequestDetails");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.Property<int>("RequestHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestHeaderId"));

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("RequestTotal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestHeaderId");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("tblRequestHeaders");
                });

            modelBuilder.Entity("Project.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CellNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.FridgeInStock", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany("FridgeInstances")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("Project.Models.FridgeVisit", b =>
                {
                    b.HasOne("Project.Models.RequestHeader", "RequestHeader")
                        .WithMany("FridgeVisits")
                        .HasForeignKey("RequestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.RequestHeader", "RequestHeader")
                        .WithMany("RequestFridges")
                        .HasForeignKey("RequestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.Navigation("FridgeInstances");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.Navigation("FridgeVisits");

                    b.Navigation("RequestFridges");
                });
#pragma warning restore 612, 618
        }
    }
}
