// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918220323_UpdateStatustFromtableRequestHeaderFromDB")]
    partial class UpdateStatustFromtableRequestHeaderFromDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FridgeId");

                    b.ToTable("tblAllocations");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCustomerS");
                });

            modelBuilder.Entity("Project.Models.Fault", b =>
                {
                    b.Property<int>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultId"));

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaintenanceVisitId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReportedByCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByTechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaultId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("MaintenanceVisitId");

                    b.HasIndex("ReportedByCustomerId");

                    b.HasIndex("ResolvedByTechnicianId");

                    b.ToTable("tblFaults");
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("tblFaultTechnicians");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FridgeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentalPricePerMonth")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("tblFridges");

                    b.HasData(
                        new
                        {
                            FridgeId = 1,
                            AvailabilityStatus = "Available",
                            Brand = "Samsung",
                            CapacityLiters = 253,
                            Condition = "Excellent",
                            Description = "Energy-efficient double door fridge with frost-free technology.",
                            FridgeNo = "FRG-001",
                            ImageUrl = "https://example.com/images/fridge1.jpg",
                            LastMaintenanceDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RT28T",
                            RentalPricePerMonth = 1200.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 2,
                            AvailabilityStatus = "Rented",
                            Brand = "LG",
                            CapacityLiters = 190,
                            Condition = "Good",
                            Description = "Compact single door fridge ideal for small apartments.",
                            FridgeNo = "FRG-002",
                            ImageUrl = "https://example.com/images/fridge2.jpg",
                            LastMaintenanceDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "GL-B201",
                            RentalPricePerMonth = 900.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 3,
                            AvailabilityStatus = "Available",
                            Brand = "Whirlpool",
                            CapacityLiters = 500,
                            Condition = "Excellent",
                            Description = "Spacious fridge with advanced cooling technology.",
                            FridgeNo = "FRG-003",
                            ImageUrl = "https://example.com/images/fridge3.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "WRT518",
                            RentalPricePerMonth = 1500.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 4,
                            AvailabilityStatus = "Available",
                            Brand = "Defy",
                            CapacityLiters = 350,
                            Condition = "Good",
                            Description = "Durable fridge with energy-saving features.",
                            FridgeNo = "FRG-004",
                            ImageUrl = "https://example.com/images/fridge4.jpg",
                            LastMaintenanceDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "DAC700",
                            RentalPricePerMonth = 1100.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 5,
                            AvailabilityStatus = "Rented",
                            Brand = "Hisense",
                            CapacityLiters = 310,
                            Condition = "Good",
                            Description = "Compact fridge with adjustable shelves.",
                            FridgeNo = "FRG-005",
                            ImageUrl = "https://example.com/images/fridge5.jpg",
                            LastMaintenanceDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "H310BI",
                            RentalPricePerMonth = 800.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 6,
                            AvailabilityStatus = "Available",
                            Brand = "Bosch",
                            CapacityLiters = 420,
                            Condition = "Excellent",
                            Description = "Premium fridge with no-frost technology.",
                            FridgeNo = "FRG-006",
                            ImageUrl = "https://example.com/images/fridge6.jpg",
                            LastMaintenanceDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "KDN42",
                            RentalPricePerMonth = 1600.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 7,
                            AvailabilityStatus = "Available",
                            Brand = "Kelvinator",
                            CapacityLiters = 250,
                            Condition = "Fair",
                            Description = "Affordable fridge with basic features.",
                            FridgeNo = "FRG-007",
                            ImageUrl = "https://example.com/images/fridge7.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "KEL250",
                            RentalPricePerMonth = 700.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 8,
                            AvailabilityStatus = "Available",
                            Brand = "Smeg",
                            CapacityLiters = 281,
                            Condition = "Excellent",
                            Description = "Retro-style fridge with modern cooling.",
                            FridgeNo = "FRG-008",
                            ImageUrl = "https://example.com/images/fridge8.jpg",
                            LastMaintenanceDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "FAB28",
                            RentalPricePerMonth = 2000.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 9,
                            AvailabilityStatus = "Rented",
                            Brand = "AEG",
                            CapacityLiters = 300,
                            Condition = "Excellent",
                            Description = "Built-in fridge with adjustable compartments.",
                            FridgeNo = "FRG-009",
                            ImageUrl = "https://example.com/images/fridge9.jpg",
                            LastMaintenanceDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "SKE818",
                            RentalPricePerMonth = 1800.0,
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 10,
                            AvailabilityStatus = "Available",
                            Brand = "Panasonic",
                            CapacityLiters = 347,
                            Condition = "Good",
                            Description = "Fridge with inverter technology for energy saving.",
                            FridgeNo = "FRG-010",
                            ImageUrl = "https://example.com/images/fridge10.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "NR-BL347",
                            RentalPricePerMonth = 1300.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 11,
                            AvailabilityStatus = "Available",
                            Brand = "Haier",
                            CapacityLiters = 565,
                            Condition = "Excellent",
                            Description = "Large capacity fridge with twin inverter technology.",
                            FridgeNo = "FRG-011",
                            ImageUrl = "https://example.com/images/fridge11.jpg",
                            LastMaintenanceDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "HRF-619",
                            RentalPricePerMonth = 2200.0,
                            Type = "Side by Side"
                        },
                        new
                        {
                            FridgeId = 12,
                            AvailabilityStatus = "Available",
                            Brand = "Hitachi",
                            CapacityLiters = 640,
                            Condition = "Excellent",
                            Description = "Premium French door fridge with eco-friendly features.",
                            FridgeNo = "FRG-012",
                            ImageUrl = "https://example.com/images/fridge12.jpg",
                            LastMaintenanceDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "R-WB640",
                            RentalPricePerMonth = 2500.0,
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 13,
                            AvailabilityStatus = "Rented",
                            Brand = "Electrolux",
                            CapacityLiters = 370,
                            Condition = "Good",
                            Description = "Fridge with taste guard deodorizer.",
                            FridgeNo = "FRG-013",
                            ImageUrl = "https://example.com/images/fridge13.jpg",
                            LastMaintenanceDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "ETB3700",
                            RentalPricePerMonth = 1400.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 14,
                            AvailabilityStatus = "Available",
                            Brand = "Sharp",
                            CapacityLiters = 600,
                            Condition = "Excellent",
                            Description = "Fridge with plasmacluster ion technology.",
                            FridgeNo = "FRG-014",
                            ImageUrl = "https://example.com/images/fridge14.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "SJ-GX60",
                            RentalPricePerMonth = 2300.0,
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 15,
                            AvailabilityStatus = "Available",
                            Brand = "Midea",
                            CapacityLiters = 400,
                            Condition = "Good",
                            Description = "Affordable fridge with large freezer compartment.",
                            FridgeNo = "FRG-015",
                            ImageUrl = "https://example.com/images/fridge15.jpg",
                            LastMaintenanceDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "HD-400",
                            RentalPricePerMonth = 1000.0,
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 16,
                            AvailabilityStatus = "Available",
                            Brand = "Gorenje",
                            CapacityLiters = 326,
                            Condition = "Good",
                            Description = "Stylish bottom freezer fridge with crisp zone for vegetables.",
                            FridgeNo = "FRG-016",
                            ImageUrl = "https://example.com/images/fridge16.jpg",
                            LastMaintenanceDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "NRK6192",
                            RentalPricePerMonth = 1250.0,
                            Type = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeId = 17,
                            AvailabilityStatus = "Available",
                            Brand = "Westinghouse",
                            CapacityLiters = 528,
                            Condition = "Excellent",
                            Description = "Family-sized fridge with humidity-controlled crisper.",
                            FridgeNo = "FRG-017",
                            ImageUrl = "https://example.com/images/fridge17.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "WBE5300",
                            RentalPricePerMonth = 1700.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 18,
                            AvailabilityStatus = "Rented",
                            Brand = "Fisher & Paykel",
                            CapacityLiters = 519,
                            Condition = "Excellent",
                            Description = "Premium French door fridge with active smart technology.",
                            FridgeNo = "FRG-018",
                            ImageUrl = "https://example.com/images/fridge18.jpg",
                            LastMaintenanceDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RF522",
                            RentalPricePerMonth = 2400.0,
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 19,
                            AvailabilityStatus = "Available",
                            Brand = "Ariston",
                            CapacityLiters = 383,
                            Condition = "Good",
                            Description = "Reliable fridge with antibacterial coating.",
                            FridgeNo = "FRG-019",
                            ImageUrl = "https://example.com/images/fridge19.jpg",
                            LastMaintenanceDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "MBA3832",
                            RentalPricePerMonth = 1150.0,
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 20,
                            AvailabilityStatus = "Available",
                            Brand = "Beko",
                            CapacityLiters = 560,
                            Condition = "Excellent",
                            Description = "Spacious bottom freezer fridge with NeoFrost cooling.",
                            FridgeNo = "FRG-020",
                            ImageUrl = "https://example.com/images/fridge20.jpg",
                            LastMaintenanceDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RCNE560",
                            RentalPricePerMonth = 1850.0,
                            Type = "Bottom Freezer"
                        });
                });

            modelBuilder.Entity("Project.Models.FridgeRequest", b =>
                {
                    b.Property<int>("FridgeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeRequestId"));

                    b.Property<string>("CapacityRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FaultyFridgeId")
                        .HasColumnType("int");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplacementFridgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeRequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FaultyFridgeId");

                    b.HasIndex("ReplacementFridgeId");

                    b.ToTable("tblFridgeRequests");
                });

            modelBuilder.Entity("Project.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceRecordId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaintenanceVisitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceRecordId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("MaintenanceVisitId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("tblMaintenanceRecords");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.Property<int>("MaintenanceVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceVisitId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceVisitId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("tblMaintenanceVisits");
                });

            modelBuilder.Entity("Project.Models.ProcessFault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduleFault")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaultId");

                    b.ToTable("tblProcessFaults");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.Property<int>("RequestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestDetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RequestHeaderId")
                        .HasColumnType("int");

                    b.HasKey("RequestDetailId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("RequestHeaderId");

                    b.ToTable("tblRequestDetais");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.Property<int>("RequestHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestHeaderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RequestTotal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestHeaderId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblRequestHeaders");
                });

            modelBuilder.Entity("Project.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CellNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("Project.Models.Fault", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.MaintenanceVisit", "MaintenanceVisit")
                        .WithMany()
                        .HasForeignKey("MaintenanceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Customer", "ReportedByCustomer")
                        .WithMany("Faults")
                        .HasForeignKey("ReportedByCustomerId");

                    b.HasOne("Project.Models.FaultTechnician", "ResolvedByTechnician")
                        .WithMany("ResolvedFaults")
                        .HasForeignKey("ResolvedByTechnicianId");

                    b.Navigation("Fridge");

                    b.Navigation("MaintenanceVisit");

                    b.Navigation("ReportedByCustomer");

                    b.Navigation("ResolvedByTechnician");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.HasOne("Project.Models.Customer", null)
                        .WithMany("Fridges")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Project.Models.FridgeRequest", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "FaultyFridge")
                        .WithMany()
                        .HasForeignKey("FaultyFridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "ReplacementFridge")
                        .WithMany()
                        .HasForeignKey("ReplacementFridgeId");

                    b.Navigation("Customer");

                    b.Navigation("FaultyFridge");

                    b.Navigation("ReplacementFridge");
                });

            modelBuilder.Entity("Project.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.MaintenanceVisit", "MaintenanceVisit")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MaintenanceVisitId");

                    b.HasOne("Project.Models.FaultTechnician", "Technician")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("MaintenanceVisit");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany("MaintenanceVisits")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId");

                    b.HasOne("Project.Models.FaultTechnician", "Technician")
                        .WithMany("MaintenanceVisits")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Fridge");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Project.Models.ProcessFault", b =>
                {
                    b.HasOne("Project.Models.Fault", "Fault")
                        .WithMany()
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fault");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.RequestHeader", "RequestHeader")
                        .WithMany()
                        .HasForeignKey("RequestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Navigation("Faults");

                    b.Navigation("Fridges");

                    b.Navigation("MaintenanceVisits");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("MaintenanceVisits");

                    b.Navigation("ResolvedFaults");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
