// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id-123",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-id-123",
                            RoleId = "admin-role-id-123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("FridgeId");

                    b.ToTable("tblAllocations", (string)null);
                });

            modelBuilder.Entity("Project.Models.BusinessInfo", b =>
                {
                    b.Property<int>("BusinessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessID");

                    b.ToTable("tblBusinessInfo", (string)null);
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("BusinessDocumentData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BusinessDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblCustomer", (string)null);
                });

            modelBuilder.Entity("Project.Models.CustomerFridge", b =>
                {
                    b.Property<int>("CustomerFridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerFridgeId"));

                    b.Property<DateTime?>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeInStockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerFridgeId");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FridgeId");

                    b.HasIndex("FridgeInStockId");

                    b.ToTable("tblCustomerFridge", (string)null);
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WorkLocationId")
                        .HasColumnType("int");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("tblCustomers");
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblEmployee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            ApplicationUserId = "admin-id-123",
                            EmployeeNumber = "EMP001"
                        });
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.Property<int>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultId"));

                    b.Property<DateTime?>("Bookingate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Completion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerBookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("FaultId");

                    b.HasIndex("VisitId");

                    b.ToTable("tblFaultTechnicians", (string)null);
                });

            modelBuilder.Entity("Project.Models.Fault", b =>
                {
                    b.Property<int>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceVisitId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReportedByCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByTechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaultId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MaintenanceVisitId");

                    b.HasIndex("ReportedByCustomerId");

                    b.HasIndex("ResolvedByTechnicianId");

                    b.ToTable("tblFaults");
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("tblFaultTechnicians");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FridgeModelId")
                        .HasColumnType("int");

                    b.Property<string>("FridgeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentalPricePerMonth")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeId");

                    b.ToTable("tblFridges", (string)null);

                    b.HasData(
                        new
                        {
                            FridgeId = 1,
                            Brand = "Samsung",
                            CapacityLiters = 253,
                            Condition = "Excellent",
                            Description = "Energy-efficient double door fridge with frost-free technology.",
                            FridgeNo = "FRG-001",
                            ImageUrl = "https://example.com/images/fridge1.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RT28T",
                            RentalPricePerMonth = 1200.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 2,
                            Brand = "LG",
                            CapacityLiters = 190,
                            Condition = "Good",
                            Description = "Compact single door fridge ideal for small apartments.",
                            FridgeNo = "FRG-002",
                            ImageUrl = "https://example.com/images/fridge2.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "GL-B201",
                            RentalPricePerMonth = 900.0,
                            Status = "Rented",
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 3,
                            Brand = "Whirlpool",
                            CapacityLiters = 500,
                            Condition = "Excellent",
                            Description = "Spacious fridge with advanced cooling technology.",
                            FridgeNo = "FRG-003",
                            ImageUrl = "https://example.com/images/fridge3.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "WRT518",
                            RentalPricePerMonth = 1500.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 4,
                            Brand = "Defy",
                            CapacityLiters = 350,
                            Condition = "Good",
                            Description = "Durable fridge with energy-saving features.",
                            FridgeNo = "FRG-004",
                            ImageUrl = "https://example.com/images/fridge4.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "DAC700",
                            RentalPricePerMonth = 1100.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 5,
                            Brand = "Hisense",
                            CapacityLiters = 310,
                            Condition = "Good",
                            Description = "Compact fridge with adjustable shelves.",
                            FridgeNo = "FRG-005",
                            ImageUrl = "https://example.com/images/fridge5.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "H310BI",
                            RentalPricePerMonth = 800.0,
                            Status = "Rented",
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 6,
                            Brand = "Bosch",
                            CapacityLiters = 420,
                            Condition = "Excellent",
                            Description = "Premium fridge with no-frost technology.",
                            FridgeNo = "FRG-006",
                            ImageUrl = "https://example.com/images/fridge6.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "KDN42",
                            RentalPricePerMonth = 1600.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 7,
                            Brand = "Kelvinator",
                            CapacityLiters = 250,
                            Condition = "Fair",
                            Description = "Affordable fridge with basic features.",
                            FridgeNo = "FRG-007",
                            ImageUrl = "https://example.com/images/fridge7.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "KEL250",
                            RentalPricePerMonth = 700.0,
                            Status = "Available",
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 8,
                            Brand = "Smeg",
                            CapacityLiters = 281,
                            Condition = "Excellent",
                            Description = "Retro-style fridge with modern cooling.",
                            FridgeNo = "FRG-008",
                            ImageUrl = "https://example.com/images/fridge8.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "FAB28",
                            RentalPricePerMonth = 2000.0,
                            Status = "Available",
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 9,
                            Brand = "AEG",
                            CapacityLiters = 300,
                            Condition = "Excellent",
                            Description = "Built-in fridge with adjustable compartments.",
                            FridgeNo = "FRG-009",
                            ImageUrl = "https://example.com/images/fridge9.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "SKE818",
                            RentalPricePerMonth = 1800.0,
                            Status = "Rented",
                            Type = "Single Door"
                        },
                        new
                        {
                            FridgeId = 10,
                            Brand = "Panasonic",
                            CapacityLiters = 347,
                            Condition = "Good",
                            Description = "Fridge with inverter technology for energy saving.",
                            FridgeNo = "FRG-010",
                            ImageUrl = "https://example.com/images/fridge10.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "NR-BL347",
                            RentalPricePerMonth = 1300.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 11,
                            Brand = "Haier",
                            CapacityLiters = 565,
                            Condition = "Excellent",
                            Description = "Large capacity fridge with twin inverter technology.",
                            FridgeNo = "FRG-011",
                            ImageUrl = "https://example.com/images/fridge11.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "HRF-619",
                            RentalPricePerMonth = 2200.0,
                            Status = "Available",
                            Type = "Side by Side"
                        },
                        new
                        {
                            FridgeId = 12,
                            Brand = "Hitachi",
                            CapacityLiters = 640,
                            Condition = "Excellent",
                            Description = "Premium French door fridge with eco-friendly features.",
                            FridgeNo = "FRG-012",
                            ImageUrl = "https://example.com/images/fridge12.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "R-WB640",
                            RentalPricePerMonth = 2500.0,
                            Status = "Available",
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 13,
                            Brand = "Electrolux",
                            CapacityLiters = 370,
                            Condition = "Good",
                            Description = "Fridge with taste guard deodorizer.",
                            FridgeNo = "FRG-013",
                            ImageUrl = "https://example.com/images/fridge13.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "ETB3700",
                            RentalPricePerMonth = 1400.0,
                            Status = "Rented",
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 14,
                            Brand = "Sharp",
                            CapacityLiters = 600,
                            Condition = "Excellent",
                            Description = "Fridge with plasmacluster ion technology.",
                            FridgeNo = "FRG-014",
                            ImageUrl = "https://example.com/images/fridge14.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "SJ-GX60",
                            RentalPricePerMonth = 2300.0,
                            Status = "Available",
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 15,
                            Brand = "Midea",
                            CapacityLiters = 400,
                            Condition = "Good",
                            Description = "Affordable fridge with large freezer compartment.",
                            FridgeNo = "FRG-015",
                            ImageUrl = "https://example.com/images/fridge15.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "HD-400",
                            RentalPricePerMonth = 1000.0,
                            Status = "Available",
                            Type = "Double Door"
                        },
                        new
                        {
                            FridgeId = 16,
                            Brand = "Gorenje",
                            CapacityLiters = 326,
                            Condition = "Good",
                            Description = "Stylish bottom freezer fridge with crisp zone for vegetables.",
                            FridgeNo = "FRG-016",
                            ImageUrl = "https://example.com/images/fridge16.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "NRK6192",
                            RentalPricePerMonth = 1250.0,
                            Status = "Available",
                            Type = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeId = 17,
                            Brand = "Westinghouse",
                            CapacityLiters = 528,
                            Condition = "Excellent",
                            Description = "Family-sized fridge with humidity-controlled crisper.",
                            FridgeNo = "FRG-017",
                            ImageUrl = "https://example.com/images/fridge17.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "WBE5300",
                            RentalPricePerMonth = 1700.0,
                            Status = "Available",
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 18,
                            Brand = "Fisher & Paykel",
                            CapacityLiters = 519,
                            Condition = "Excellent",
                            Description = "Premium French door fridge with active smart technology.",
                            FridgeNo = "FRG-018",
                            ImageUrl = "https://example.com/images/fridge18.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RF522",
                            RentalPricePerMonth = 2400.0,
                            Status = "Rented",
                            Type = "French Door"
                        },
                        new
                        {
                            FridgeId = 19,
                            Brand = "Ariston",
                            CapacityLiters = 383,
                            Condition = "Good",
                            Description = "Reliable fridge with antibacterial coating.",
                            FridgeNo = "FRG-019",
                            ImageUrl = "https://example.com/images/fridge19.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "MBA3832",
                            RentalPricePerMonth = 1150.0,
                            Status = "Available",
                            Type = "Top Freezer"
                        },
                        new
                        {
                            FridgeId = 20,
                            Brand = "Beko",
                            CapacityLiters = 560,
                            Condition = "Excellent",
                            Description = "Spacious bottom freezer fridge with NeoFrost cooling.",
                            FridgeNo = "FRG-020",
                            ImageUrl = "https://example.com/images/fridge20.jpg",
                            IsRented = false,
                            LastMaintenanceDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Available",
                            Model = "RCNE560",
                            RentalPricePerMonth = 1850.0,
                            Status = "Available",
                            Type = "Bottom Freezer"
                        });
                });

            modelBuilder.Entity("Project.Models.FridgeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityLiters")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EnergyRating")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("HasDigitalDisplay")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGlassDoor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLock")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFrostFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScrapped")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MonthlyRentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PowerConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReorderQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceIntervalMonths")
                        .HasColumnType("int");

                    b.Property<string>("TemperatureRange")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("tblFridgeInStocks", (string)null);

                    b.Property<string>("Voltage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarrantyPeriodMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FridgeModel");
                });

            modelBuilder.Entity("Project.Models.FridgeRequest", b =>
                {
                    b.Property<int>("FridgeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeRequestId"));

                    b.Property<string>("CapacityRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FaultyFridgeId")
                        .HasColumnType("int");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplacementFridgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FridgeRequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FaultyFridgeId");

                    b.HasIndex("ReplacementFridgeId");

                    b.ToTable("tblFridgeRequests");
                });

            modelBuilder.Entity("Project.Models.FridgeVisit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("CheckupStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerApproval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("AllocationId");

                    b.HasIndex("RequestHeaderId");

                    b.ToTable("tblFridgeVisits", (string)null);
                });

            modelBuilder.Entity("Project.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblLocations");
                });

            modelBuilder.Entity("Project.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceRecordId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaintenanceVisitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceRecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("MaintenanceVisitId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("tblMaintenanceRecords");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.Property<int>("MaintenanceVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceVisitId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FridgeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceVisitId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("tblMaintenanceVisits");
                });

            modelBuilder.Entity("Project.Models.ProcessFault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduleFault")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaultId");

                    b.ToTable("tblProcessFaults");
                });

            modelBuilder.Entity("Project.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ApprovedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequiredByDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("RequestedById");

                    b.HasIndex("SupplierId");

                    b.ToTable("tblPurchaseRequests");
                });

            modelBuilder.Entity("Project.Models.PurchaseRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EstimatedUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FridgeModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PurchaseRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.HasIndex("PurchaseRequestId");

                    b.ToTable("tblPurchaseRequestItems");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.Property<int>("RequestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestDetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<int?>("FridgeModelId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RequestHeaderId")
                        .HasColumnType("int");

                    b.HasKey("RequestDetailId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("FridgeModelId");

                    b.HasIndex("RequestHeaderId");

                    b.ToTable("tblRequestDetais", (string)null);
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.Property<int>("RequestHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestHeaderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("RequestTotal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestHeaderId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("tblRequestHeaders");
                });

            modelBuilder.Entity("Project.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierId");

                    b.HasIndex("LocationId");

                    b.ToTable("tblRequestHeaders", (string)null);
                });

            modelBuilder.Entity("Project.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CellNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "admin-id-123",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cb49037-e10d-4f6c-9178-c080e6497ccf",
                            Email = "admin@fridgesystem.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FRIDGESYSTEM.COM",
                            NormalizedUserName = "ADMIN@FRIDGESYSTEM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAX+7/D0OxRGayk4zBpVKz7f2DqGYeZJE3dlW/mqxmcaSB7YRzMiHNYSFVP+9LAJzg==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2011129e-5e59-4e82-b591-c8405469ed82",
                            TwoFactorEnabled = false,
                            UserName = "admin@fridgesystem.com",
                            CellNumber = "+27123456789",
                            City = "Johannesburg",
                            FirstName = "System",
                            IsApproved = true,
                            LastName = "Administrator",
                            PostalCode = "2000",
                            State = "Gauteng",
                            Status = "Approved",
                            StreetAddress = "123 Admin Street"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("AllocatedFridges")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("ProcessedAllocations")
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Location", null)
                        .WithMany("FridgeAllocations")
                        .HasForeignKey("LocationId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Fridge");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.CustomerFridge", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.FridgeInStock", "FridgeInStock")
                        .WithMany()
                        .HasForeignKey("FridgeInStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Fridge");

                    b.Navigation("FridgeInStock");
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.HasOne("Project.Models.FridgeVisit", "FridgeVisit")
                        .WithMany("FaultTechnicians")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeVisit");
                });

            modelBuilder.Entity("Project.Models.FridgeInStock", b =>
                {
                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("AssignedFaults")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Location", null)
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId");

                    b.HasOne("Project.Models.MaintenanceVisit", "MaintenanceVisit")
                        .WithMany()
                        .HasForeignKey("MaintenanceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Customer", "ReportedByCustomer")
                        .WithMany()
                        .HasForeignKey("ReportedByCustomerId");

                    b.HasOne("Project.Models.FaultTechnician", "ResolvedByTechnician")
                        .WithMany("ResolvedFaults")
                        .HasForeignKey("ResolvedByTechnicianId");

                    b.Navigation("Fridge");

                    b.Navigation("MaintenanceVisit");

                    b.Navigation("ReportedByCustomer");

                    b.Navigation("ResolvedByTechnician");
                });

            modelBuilder.Entity("Project.Models.Fridge", b =>
                {
                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("ManagedFridges")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Project.Models.FridgeModel", null)
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId");

                    b.HasOne("Project.Models.Location", null)
                        .WithMany("Fridges")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Project.Models.FridgeRequest", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "FaultyFridge")
                        .WithMany()
                        .HasForeignKey("FaultyFridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Fridge", "ReplacementFridge")
                        .WithMany()
                        .HasForeignKey("ReplacementFridgeId");

                    b.Navigation("Customer");

                    b.Navigation("FaultyFridge");

                    b.Navigation("ReplacementFridge");
                });

            modelBuilder.Entity("Project.Models.FridgeVisit", b =>
                {
                    b.HasOne("Project.Models.Allocation", null)
                        .WithMany("FridgeVisits")
                        .HasForeignKey("AllocationId");

                    b.HasOne("Project.Models.RequestHeader", "RequestHeader")
                        .WithMany("FridgeVisits")
                        .HasForeignKey("RequestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("Project.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.MaintenanceVisit", "MaintenanceVisit")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MaintenanceVisitId");

                    b.HasOne("Project.Models.FaultTechnician", "Technician")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("MaintenanceVisit");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.HasOne("Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Employee", null)
                        .WithMany("MaintenanceVisits")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId");

                    b.HasOne("Project.Models.Location", null)
                        .WithMany("MaintenanceVisits")
                        .HasForeignKey("LocationId");

                    b.HasOne("Project.Models.FaultTechnician", "Technician")
                        .WithMany("MaintenanceVisits")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Fridge");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Project.Models.ProcessFault", b =>
                {
                    b.HasOne("Project.Models.Fault", "Fault")
                        .WithMany()
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fault");
                });

            modelBuilder.Entity("Project.Models.PurchaseRequest", b =>
                {
                    b.HasOne("Project.Models.Employee", "ApprovedBy")
                        .WithMany("ApprovedPurchaseRequests")
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Project.Models.Employee", "RequestedBy")
                        .WithMany("RequestedPurchaseRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Supplier", null)
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("SupplierId");

                    b.Navigation("ApprovedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Project.Models.PurchaseRequestItem", b =>
                {
                    b.HasOne("Project.Models.FridgeModel", "FridgeModel")
                        .WithMany()
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("Project.Models.RequestDetails", b =>
                {
                    b.HasOne("Project.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.FridgeModel", null)
                        .WithMany("AllocationRequestDetails")
                        .HasForeignKey("FridgeModelId");

                    b.HasOne("Project.Models.RequestHeader", "RequestHeader")
                        .WithMany("RequestFridges")
                        .HasForeignKey("RequestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.HasOne("Project.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Project.Models.Supplier", b =>
                {
                    b.HasOne("Project.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Project.Models.Allocation", b =>
                {
                    b.Navigation("FridgeVisits");
                });

            modelBuilder.Entity("Project.Models.Employee", b =>
                {
                    b.Navigation("AllocatedFridges");

                    b.Navigation("ApprovedPurchaseRequests");

                    b.Navigation("AssignedFaults");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("MaintenanceVisits");

                    b.Navigation("ManagedCustomers");

                    b.Navigation("ManagedFridges");

                    b.Navigation("ProcessedAllocations");

                    b.Navigation("RequestedPurchaseRequests");
                });

            modelBuilder.Entity("Project.Models.FaultTechnician", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("MaintenanceVisits");

                    b.Navigation("ResolvedFaults");
                });

            modelBuilder.Entity("Project.Models.FridgeModel", b =>
                {
                    b.Navigation("AllocationRequestDetails");

                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("Project.Models.Location", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");

                    b.Navigation("FaultReports");

                    b.Navigation("FridgeAllocations");

                    b.Navigation("Fridges");

                    b.Navigation("MaintenanceVisits");
                });

            modelBuilder.Entity("Project.Models.MaintenanceVisit", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("Project.Models.PurchaseRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Project.Models.FridgeVisit", b =>
                {
                    b.Navigation("FaultTechnicians");
                });

            modelBuilder.Entity("Project.Models.RequestHeader", b =>
                {
                    b.Navigation("FridgeVisits");

                    b.Navigation("RequestFridges");
                });

            modelBuilder.Entity("Project.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
